# Generated by Django 3.0 on 2021-08-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
