# Generated by Django 3.0 on 2021-08-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_id',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_id',
            new_name='state_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_id',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Area')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.City')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.State')),
            ],
        ),
    ]
