# Generated by Django 3.0 on 2021-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
