# Generated by Django 3.0 on 2021-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210814_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='is_active',
            field=models.CharField(default='inactive', max_length=300),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.CharField(default='inactive', max_length=300),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_active',
            field=models.CharField(default='inactive', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.CharField(default='inactive', max_length=300),
        ),
    ]
