# Generated by Django 3.0 on 2021-08-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210816_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_logout',
        ),
    ]
